export const products = [
  {
    _id: '1',
    name: 'Áo Khoác Nam Thể Thao Mùa Đông Cao Cấp',
    image: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?q=80&w=1887&auto=format&fit=crop',
    description: 'Áo khoác thể thao mùa đông, giữ nhiệt cực tốt với công nghệ Omni-Heat. Phù hợp cho các hoạt động ngoài trời, kiểu dáng hiện đại mang đến sự tự tin.',
    brand: 'T-Brand',
    category: 'Áo Khoác',
    price: 850000,
    countInStock: 10,
    colors: ['Đen', 'Xám', 'Xanh Navy'],
    sizes: ['M', 'L', 'XL'],
  },
  {
    _id: '2',
    name: 'Áo Thun Nam Cổ Tròn Cotton 100% Thoáng Mát',
    image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?q=80&w=1780&auto=format&fit=crop',
    description: 'Chất liệu 100% cotton tự nhiên, thấm hút mồ hôi siêu tốt. Phù hợp dạo phố, đi chơi, mặc ở nhà. Mix map dễ dàng với Jean hoặc Kaki.',
    brand: 'T-Brand',
    category: 'Áo Thun',
    price: 250000,
    countInStock: 25,
    colors: ['Trắng', 'Đen'],
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    _id: '3',
    name: 'Quần Jeans Nam Xanh Rêu Phom Slim-fit',
    image: 'https://images.unsplash.com/photo-1542272454315-4c01d711fa7f?q=80&w=1964&auto=format&fit=crop',
    description: 'Quần jeans phom dáng slim-fit ôm nhẹ, giúp tôn lên đôi chân, cực kỳ thời trang và nam tính. Vải co giãn 4 chiều.',
    brand: 'Denim V',
    category: 'Quần',
    price: 490000,
    countInStock: 0, // Hết hàng để test Use Case
    colors: ['Xanh Rêu'],
    sizes: ['29', '30', '31', '32'],
  },
  {
    _id: '4',
    name: 'Váy Liền Thân Nữ Tính Thanh Lịch',
    image: 'https://images.unsplash.com/photo-1515347619362-e67490035515?q=80&w=1887&auto=format&fit=crop',
    description: 'Chiếc váy tinh tế cho những buổi hẹn hò hoặc dạo phố. Màu đỏ bordeaux rực rỡ thu hút mọi ánh nhìn.',
    brand: 'Elegance',
    category: 'Váy Nữ',
    price: 650000,
    countInStock: 5,
    colors: ['Đỏ bordeaux', 'Đen'],
    sizes: ['S', 'M', 'L'],
  },
  {
    _id: '5',
    name: 'Áo Hoodie Nam Nữ Form Rộng Unisex',
    image: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?q=80&w=1887&auto=format&fit=crop',
    description: 'Phong cách đường phố năng động. Áo hoodie form rộng, chất nỉ bông ấm áp, màu xám khói dễ phối đồ.',
    brand: 'StreetW',
    category: 'Áo Khoác',
    price: 320000,
    countInStock: 15,
    colors: ['Xám', 'Trắng'],
    sizes: ['M', 'L', 'XL', 'XXL'],
  },
  {
    _id: '6',
    name: 'Quần Kaki Túi Hộp Xanh Quân Đội',
    image: 'https://images.unsplash.com/photo-1555689986-2748a049d5bf?q=80&w=1925&auto=format&fit=crop',
    description: 'Quần túi hộp mang phong cách cargo hầm hố. Chất vải kaki dày dặn, bền bỉ với nhiều túi chứa đồ tiện lợi.',
    brand: 'CargoM',
    category: 'Quần',
    price: 400000,
    countInStock: 8,
    colors: ['Xanh Quân Đội', 'Xám Đen'],
    sizes: ['30', '31', '32', '34'],
  },
  {
    _id: '7',
    name: 'Áo Sơ Mi Nam Công Sở Tay Cài',
    image: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?q=80&w=2000&auto=format&fit=crop',
    description: 'Áo sơ mi cao cấp, form ôm vừa vặn, thích hợp đi làm văn phòng hoặc sự kiện.',
    brand: 'T-Brand',
    category: 'Áo Sơ Mi',
    price: 380000,
    countInStock: 20,
    colors: ['Trắng', 'Xanh Nhạt'],
    sizes: ['M', 'L', 'XL'],
  }
];
